name: 'Add checks'
description: 'Add status check to a PR.'
inputs:
  name:
    description: 'name of check'
    required: true
  head-sha:
    description: 'head-sha'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/github-script@v6
      env:
        name: ${{ inputs.name }}
        head_sha: ${{ inputs.head-sha }}
      with:
        script: |
          const { name, head_sha } = process.env;
          github.rest.checks.create({
            name,
            owner: context.repo.owner,
            repo: context.repo.repo,
            head_sha,
            status: 'completed',
            conclusion: 'success'
          })
