name: 'Add checks'
description: 'Add status check to a PR.'
inputs:
  name:
    description: 'name of check'
    required: true
  status:
    description: 'status of check'
    required: true
  head-sha:
    description: 'head-sha'
    required: true
  conclusion:
    description: 'add conclusion if status is completed'
    required: false
runs:
  using: 'composite'
  steps:
    - uses: actions/github-script@v6
      env:
        name: ${{ inputs.name }}
        head_sha: ${{ inputs.head-sha }}
        status: ${{ inputs.status }}
        conclusion: ${{ inputs.conclusion }}
      with:
        script: |
          const { name, head_sha, status, conclusion } = process.env;
          github.rest.checks.create({
            name,
            owner: context.repo.owner,
            repo: context.repo.repo,
            head_sha,
            status,
            conclusion: conclusion ? conclusion : undefined
          });
