name: 'Update Status Checks'
description: 'Update status check on a specified check ID'
inputs:
  status:
    description: >-
      Status of check with possible values of 'queued', 'in_progress', 'completed'
    required: true
  check_id:
    description: 'Check ID of status check to be updated'
    required: true
  conclusion:
    description: >-
      Conclusion of status check with possible values of 'action_required',
      'cancelled', 'failure', 'neutral', 'success', 'skipped', 'stale', 'timed_out'.
      This is only required if status is 'completed'.
    required: false
runs:
  using: 'composite'
  steps:
    - uses: actions/github-script@v6
      env:
        status: ${{ inputs.status }}
        check_run_id: ${{ inputs.check_id }}
        conclusion: ${{ inputs.conclusion }}
      with:
        script: |
          const { status, conclusion, check_run_id } = process.env;
          const { owner, repo } = context.repo;
          github.rest.checks.update({
            owner,
            repo,
            status,
            check_run_id,
            conclusion: conclusion.length > 0 ? conclusion : undefined
          });
