export enum ComponentClassNames {
  Badge = 'amplify-badge',
  Button = 'amplify-button',
  Card = 'amplify-card',
  CheckboxField = 'amplify-checkboxfield',
  CheckboxFieldBox = 'amplify-checkboxfield__box',
  CheckboxFieldIcon = 'amplify-checkboxfield__icon',
  CheckboxFieldLabel = 'amplify-checkboxfield__label',
  Divider = 'amplify-divider',
  FieldDescription = 'amplify-field__description',
  FieldErrorMessage = 'amplify-field__error-message',
  FieldWrapper = 'amplify-textfield-wrapper',
  Flex = 'amplify-flex',
  Heading = 'amplify-heading',
  Icon = 'amplify-icon',
  Image = 'amplify-image',
  Input = 'amplify-input',
  Label = 'amplify-label',
  Pagination = 'amplify-pagination',
  Placeholder = 'amplify-placeholder',
  Rating = 'amplify-rating',
  Select = 'amplify-select',
  Text = 'amplify-text',
  TextField = 'amplify-textfield',
  View = 'amplify-view',
}
