name: POC / Pull Environments

on:
  pull_request:
    branches: [main]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - run: echo "HI"
