# Description: this is a reusable workflow that runs unit tests.
#
# See `./test-prs.yml` to see an example usage.

on:
  workflow_call:
    inputs:
      commit:
        # commit to run tests against
        required: true
        type: string
      repository:
        # repository to run tests against (possibly a fork of amplify-ui)
        required: true
        type: string

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        package:
          - ui
          - angular
          - vue
          - react
          - react-native
          - react-core

    steps:
      - name: Checkout Amplify UI
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commit }}
          repository: ${{ inputs.repository }}
          persist-credentials: false

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2

      - name: Restore node_modules cache
        uses: actions/cache@v3
        id: restore-cache
        with:
          path: |
            ./node_modules
            **/node_modules
          key: ${{ runner.os }}-nodemodules-${{ inputs.commit }}
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 3

      - name: Restore ui/dist cache
        uses: actions/cache@v3
        id: restore-ui-cache
        with:
          path: ./packages/ui/dist
          key: ${{ runner.os }}-ui-${{ inputs.commit }}
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1

      - name: Install packages
        if: steps.restore-cache.outputs.cache-hit != 'true'
        uses: ./.github/actions/install-with-retries
        with:
          skip-cypress-binary: true # unit test doesn't need cypress

      - name: Build ui package
        if: ${{ steps.restore-ui-cache.outputs.cache-hit != 'true'  }}
        run: yarn ui build

      - name: Build react-core package
        if: ${{ matrix.package == 'react' || matrix.package == 'react-native' }}
        run: yarn react-core build

      - name: Build ${{ matrix.package }} package
        if: ${{ matrix.package != 'ui' }}
        run: yarn ${{ matrix.package }} build

      - name: Check ${{ matrix.package }} bundle size
        if: ${{ matrix.package == 'react' }}
        run: yarn react size

      - name: Cache ${{ matrix.package }}/dist
        uses: actions/cache@v3
        with:
          path: ./packages/${{ matrix.package }}/dist
          key: ${{ runner.os }}-${{ matrix.package }}-${{ inputs.commit }}

      - name: Lint packages
        run: yarn ${{ matrix.package }} lint

      - name: Run ${{ matrix.package }} CI tests
        run: yarn ${{ matrix.package }} test:ci
