# Description: This workflow runs unit, e2e, codeql, and dependency review
#              against internal PRs 
#
# Triggered by:
#   (1) Opening a pull request
#   (2) On every commit to the PR
#   (3) Adding run-tests label to the PR

name: Test / PRs

concurrency:
  group: test-internal-prs-${{ github.event.pull_request.id }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, labeled]

permissions:
  pull-requests: write # used to remove label
  id-token: write # This is required for requesting the JWT
  statuses: write # This is required for running set-status actions
  # other permissions are defaulted to "none"

jobs:
  setup:
    runs-on: ubuntu-latest
    # We run tests only if it's not from a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Remove run-tests label, if applicable
        if: always() && github.event.label.name == 'run-tests'
        env:
          ISSUE_NUMBER: ${{ github.event.pull_request.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          LABEL_NAME: 'run-tests'
        uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975 # v6.4.0 https://github.com/actions/github-script/commit/98814c53be79b1d30f795b907e553d8679345975
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { ISSUE_NUMBER, REPO_OWNER, REPO_NAME, LABEL_NAME } = process.env
            github.rest.issues.removeLabel({ owner: REPO_OWNER, repo: REPO_NAME, issue_number: ISSUE_NUMBER, name: LABEL_NAME })
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: Set status to commit sha
        uses: ./.github/actions/set-status
        with:
          sha: ${{ github.sha }}
          state: 'pending'
          context: 'Run PR checks'
          description: 'PR checks are now running'
          # URL below is a link to the current workflow run to allow users to see the status of the workflow.
          target-url: https://github.com/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}

  dependency-review:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3

  codeql:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [javascript]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
          config-file: ./.github/codeql/codeql-config.yml
          queries: +security-and-quality

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: '/language:${{ matrix.language }}'

  setup-cache:
    needs: setup
    uses: ./.github/workflows/reusable-setup-cache.yml
    with:
      commit: ${{ github.sha }}
      repository: ${{ github.repository }}

  unit:
    uses: ./.github/workflows/reusable-unit.yml
    needs: setup-cache
    with:
      commit: ${{ github.sha }}
      repository: ${{ github.repository }}

  e2e:
    uses: ./.github/workflows/reusable-e2e.yml
    needs: unit
    with:
      commit: ${{ github.event.pull_request.head.sha }}
      repository: ${{ github.event.pull_request.head.repo.full_name }}
    secrets:
      AUTH_E2E_ROLE_ARN: ${{ secrets.AUTH_E2E_ROLE_ARN }}
      DATASTORE_E2E_ROLE_ARN: ${{ secrets.DATASTORE_E2E_ROLE_ARN }}
      GEO_E2E_ROLE_ARN: ${{ secrets.GEO_E2E_ROLE_ARN }}
      STORAGE_E2E_ROLE_ARN: ${{ secrets.STORAGE_E2E_ROLE_ARN }}
      IN_APP_MESSAGING_E2E_ROLE_ARN: ${{ secrets.IN_APP_MESSAGING_E2E_ROLE_ARN }}
      DOMAIN: ${{ secrets.DOMAIN }}
      PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
      USERNAME: ${{ secrets.USERNAME }}
      NEW_PASSWORD: ${{ secrets.NEW_PASSWORD }}
      VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
      SITE_URL: ${{ secrets.SITE_URL }}
      DOCSEARCH_DOCS_APP_ID: ${{ secrets.DOCSEARCH_DOCS_APP_ID }}
      DOCSEARCH_DOCS_API_KEY: ${{ secrets.DOCSEARCH_DOCS_API_KEY }}
      DOCSEARCH_DOCS_INDEX_NAME: ${{ secrets.DOCSEARCH_DOCS_INDEX_NAME }}

 # update status on success
  update-success-status:
    if: ${{ success() }}
    needs: [setup, e2e, codeql, dependency-review]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c #v3.3.0 https://github.com/actions/checkout/commit/ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Update status when tests are successful
        uses: ./.github/actions/set-status
        with:
          sha: ${{ github.sha }}
          state: 'success'
          context: 'Run PR checks'
          description: 'PR checks have finished running'
          target-url: https://github.com/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}

  # update status on failure
  update-failure-status:
    if: ${{ failure() }}
    needs: [setup, e2e, codeql, dependency-review]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c #v3.3.0 https://github.com/actions/checkout/commit/ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Update status when tests are not successful
        uses: ./.github/actions/set-status
        with:
          sha: ${{ github.sha }}
          state: 'failure'
          context: 'Run PR checks'
          description: 'PR checks have failed'
          target-url: https://github.com/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}
